version: 2.1

common: &common
  working_directory: ~/repo

jobs:
  linux-test:
    <<: *common
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: ensure nightly is default and upgrade
          command: |
            rustup default nightly
            rustup update
      - run:
          name: test
          command: cargo test --workspace

  linux-wasm-test:
    <<: *common
    docker:
      - image: davesque/rust-wasm
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: ensure nightly is default and upgrade
          command: |
            rustup default nightly
            rustup update
      - run:
          name: test
          command: wasm-pack test --node -- --workspace

  coverage:
    <<: *common
    machine: true
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: coverage with tarpaulin
          command: |
            docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin:latest-nightly cargo tarpaulin --all --verbose --out Xml
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test:
    jobs:
      - linux-test
      - linux-wasm-test
      - coverage
