[package]
name = "rust-vyper-parser"
version = "0.1.0"
authors = ["David Sanders <david@ethereum.org>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/davesque/rust-vyper"
description = "Parser lib for rust-vyper."

[dependencies]
nom = "5"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
str-concat = "0.1.4"

[dev-dependencies]
pyo3 = "0.8"
difference = "2.0"
