[package]
name = "vyper-parser"
version = "0.1.0"
authors = ["David Sanders <david@ethereum.org>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/davesque/rust-vyper"
description = "Parser lib for Rust Vyper."

[dependencies]
nom = "5"
regex = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
difference = "2.0"
pyo3 = "0.8.2"
ron = "0.5.1"
serde_json = "1"
